### PR TITLE
Audit/sommelier 3

### PR DESCRIPTION
**Pull request by paulczajka**
### View the Final Report locally

```bash
# Getting the `library` repo for the first time:
git clone git@github.com:0xMacro/library.git
git submodule init
git submodule update  # requires you have a github SSH key
npm install
npm run init

# Checkout and run the Sommelier-3 PR branch:
git pull
git checkout audit/sommelier-3
npm run dev

# Now open http://localhost:7272/library/audits/sommelier-3 in a browser
```

### Final Report content notes

**Please focus just on _issue text_ content for now**

*Content changes from Prelims*
- L-5 is now Q-10
- I-9 is now to Q-11
- New I-9: updated PriceRouter in Registry
- New I-10: _previewWithdraw small-value issue
- G-1 and G-2 dropped: not sufficient savings to warrant development work

*TODO*
- Update to `commitTree` hash when change is ready
- Update surrounding report text
- Move I-7 to different categorization/severity?
- Create Issue for `asset` mutability: https://www.notion.so/0xmacro/Sommelier-3-Client-Fixes-internal-436b835c774547298dea0dec093b078c#63be8f09b790428c9caa95daed153727

### CODE REVIEW

**Comment by abhishekvispute** [comment]
I reviewed H1, H2. M5 and M6

**For H1**

image
consider adding space between ``totalAssets`` and ``being``


consider removing this ** ** for all actions in this code block 
image
S

consider removing combining this two sections into one
image


All else LGTM :tada:

**Comment by exp7l** [comment]
# H3   Oracle latency allows arbitrage 

Consider changing 
"Valuation of positions = sum(exchangeRate * position)" to
"Valuation of positions = sum(exchangeRate_holdingpos-pos * position) for all cellar position"
_To be slightly more specific._

Consider changing 
"Arbitrager: Redeems 50% shares: receives 100.5MM USDC risk-free" to
"Arbitrager: Redeems 50% shares: receives 100.5MM USDC worth of WETH, making 0.5MM USDC worth of WETH risk-free-profit"
_To be more specific with the units_

Consider changing:
"Total assets: (1MM WETH * 101MM WETH-USDC) + 100MM USDC = 201MM USDC" to
"Total assets: (1MM WETH @ WETH-USDC 101) + 100MM USDC = 201MM USDC".
_For an accurate calculation_

Consider removing 
"Limit arbitrager from using flash loans.". 
_A sandwich attack around an oracle update need to be 3 transactions, making flash loan not possible._

Consider changing
"Consider to find breaking usecases."
"Consider finding breaking usecases."
_Grammar_

Consider adding info (to Somm's comment)
"shareLockPeriod defaulted to be locked for 10 blocks, and can be changed by governance."
_It is now 7200 blocks (or 1 day assuming 12 seconds/block)_
https://github.com/PeggyJV/cellar-contracts/blob/f3ab4812bcd2bdcc65d2d4eb4ebf27189de9d7bd/src/base/Cellar.sol#L756

# M-7  Price oracle with no redundancy can lead to arbitrage 

LGTM

# M-8  _convertToFees Underflow Leading to Denial of Service by Force Feeding 

LGTM

# I-5  Performance fee applies to unrealized yield leading to excessive fees for lps 

LGTM

# I-6  ERC4626 non-compliance: maxWithdraw() over-estimates by not considering fees 

LGTM

# I-6-1 (the IDs look off starting here)  Governance privilege to add manipulable position is not removable 

Consider fixing the ID, otherwise LGTM 

# I-7  Blockchain transparency can create incentives for copying strategy 

LGTM

# I-9  _previewWithdraw() misreports for very small asset values 

LGTM

# Q-11  FAQs Not Compatible with Each Other 

LGTM

**Comment by paulczajka** [comment]
> I reviewed H1, H2, M5, M6, Q9, Q10 Please let me know if there is anything else I need to review...

Fixed

**Comment by paulczajka** [comment]
> # H3 Oracle latency allows arbitrage...

Fixed all noted issues

**Pull request merged**
